{% set version = "0.10.26" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rmysql
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/RMySQL_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/RMySQL/RMySQL_{{ version }}.tar.gz
  sha256: 45bb5b20a38b1f7d3a58a1c15c9d57707d603b01a3021423d1d57367a4ef637a

build:
  merge_build_host: true  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}sed               # [win]
    - {{ posix }}grep              # [win]
    - {{ posix }}autoconf
    - {{ posix }}automake          # [not win]
    - {{ posix }}automake-wrapper  # [win]
    - {{ posix }}pkg-config
    - {{ posix }}make
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - mysql-connector-c
    - r-dbi >=0.4
  run:
    - r-base
    - mysql-connector-c
    - {{ native }}gcc-libs         # [win]
    - r-dbi >=0.4

test:
  commands:
    - $R -e "library('RMySQL')"           # [not win]
    - "\"%R%\" -e \"library('RMySQL')\""  # [win]

about:
  home: https://downloads.mariadb.org/connector-c/ (upstream)
  license: GPL-2.0-only
  summary: Legacy 'DBI' interface to 'MySQL' / 'MariaDB' based on old code ported from S-PLUS. A modern 'MySQL' client based on 'Rcpp' is available  from the 'RMariaDB' package.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: RMySQL
# Version: 0.10.17
# Title: Database Interface and 'MySQL' Driver for R
# Description: Legacy 'DBI' interface to 'MySQL' / 'MariaDB' based on old code ported from S-PLUS. A modern 'MySQL' client based on 'Rcpp' is available  from the 'RMariaDB' package.
# Authors@R: c(person("Jeroen", "Ooms", email = "jeroen@berkeley.edu",  role = c("aut", "cre"), comment = c(ORCID = "0000-0002-4035-0289")), person("David", "James", role = "aut"), person("Saikat", "DebRoy", role = "aut"), person("Hadley", "Wickham", email = "hadley@rstudio.com", role = "aut"), person("Jeffrey", "Horner", role = "aut"), person("RStudio", role = "cph"))
# Depends: R (>= 2.8.0), DBI (>= 0.4)
# Imports: methods
# License: GPL-2
# URL: https://downloads.mariadb.org/connector-c/ (upstream)
# BugReports: https://github.com/r-dbi/rmysql/issues
# SystemRequirements: libmariadb-client-dev | libmariadb-client-lgpl-dev | libmysqlclient-dev (deb), mariadb-devel (rpm), mariadb | mysql-connector-c (brew), mysql56_dev (csw)
# NeedsCompilation: yes
# Collate: 'mysql.R' 'driver.R' 'connection.R' 'data-type.R' 'default.R' 'escaping.R' 'result.R' 'extension.R' 'is-valid.R' 'table.R' 'transaction.R'
# Suggests: RMariaDB, testthat, curl
# Packaged: 2019-03-04 13:25:49 UTC; jeroen
# Author: Jeroen Ooms [aut, cre] (<https://orcid.org/0000-0002-4035-0289>), David James [aut], Saikat DebRoy [aut], Hadley Wickham [aut], Jeffrey Horner [aut], RStudio [cph]
# Maintainer: Jeroen Ooms <jeroen@berkeley.edu>
# Repository: CRAN
# Date/Publication: 2019-03-04 15:10:03 UTC
