appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: F29sSve6MSiWQsq1jAD9Gsdjmqqgxf1sVqLfTsbuLKqpdbKzFmqEZGgEf8Itx8Hb14mcxxUImtkpMU12KZLBRFR3+WPv6iavOzlwlHMpFKUXJdDnFni55a8BenH0elWgQLIqMxwgbmZwXbbd9n+UM2AyaB/l2YOgV/3m+5xrWo5ExRuP+89HKdq1IglREZNZFag4yEDfnw21RXDaY9+kYoS1ZSNsY8TvOtKNoPTXdqOLRqko0B6QpBxTPtl+As8ciCTEkdOyz0g5lqu4l0m8Eg2ZKFinYyXVhJe3GTGXHznFDeTvCktC4BZvwORmNIv0wIwoZEguqR0E/Qb29qefqw1GbjWWdz7q+D+ALS27wrViFwGQdvXvIFU1MhsrQ+zGSIeKmpcxsftQRHIfN8TSD6dug8qEOBrFiDacVXKk52f7MWRzvrt3bNNjRBoUVLlO/sA5OIvDQqKFkqCSeDlQQkvZmrluR3HYqgExezzrJwmddnORoqSUN6zxgeo1AuSi3Rruwt8wx0gvQnPkLt4ibyOg2Ncka2vScZSGO1blDe+ZEnoSHmsoXMCeEiZ5DgY7E2R4ZP9onzHXaHRGNkEwV3wSj1vv9DCub0iy2mxQ1zCPGJIjqs07SaCDva+vRBpoMcnmDIWI2hJ2GMj39Kkp0KmJTrTN1OtyXB4bM1cA6I0=}
bot:
  automerge: true
